using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Ferrara.Compass.Abstractions.Constants
{
    public class StageGateConsolidatedFinancialSummaryListFields
    {
        public const string Title = "Title";
        public const string StageGateProjectListItemId = "StageGateProjectListItemId";

        public const string Gate = "Gate";
        public const string BriefNumber = "BriefNumber";
        public const string BriefName = "BriefName";
        public const string BriefSummary = "BriefSummary";
        public const string Name = "Name";
        public const string AverageTargetMargin = "AverageTargetMargin";
        public const string DispConsFinInProjBrief = "DispConsFinInProjBrief";
        public const string VolumeTotal1 = "VolumeTotal1";
        public const string VolumeIncremental1 = "VolumeIncremental1";
        public const string GrossSalesTotal1 = "GrossSalesTotal1";
        public const string GrossSalesIncremental1 = "GrossSalesIncremental1";
        public const string NetSalesTotal1 = "NetSalesTotal1";
        public const string NetSalesIncremental1 = "NetSalesIncremental1";
        public const string COGSTotal1 = "COGSTotal1";
        public const string COGSIncremental1 = "COGSIncremental1";
        public const string GrossMarginTotal1 = "GrossMarginTotal1";
        public const string GrossMarginIncremental1 = "GrossMarginIncremental1";
        public const string GrossMarginPctTotal1 = "GrossMarginPctTotal1";
        public const string GrossMarginPctIncremental1 = "GrossMarginPctIncremental1";
        public const string VolumeTotal2 = "VolumeTotal2";
        public const string VolumeIncremental2 = "VolumeIncremental2";
        public const string GrossSalesTotal2 = "GrossSalesTotal2";
        public const string GrossSalesIncremental2 = "GrossSalesIncremental2";
        public const string NetSalesTotal2 = "NetSalesTotal2";
        public const string NetSalesIncremental2 = "NetSalesIncremental2";
        public const string COGSTotal2 = "COGSTotal2";
        public const string COGSIncremental2 = "COGSIncremental2";
        public const string GrossMarginTotal2 = "GrossMarginTotal2";
        public const string GrossMarginIncremental2 = "GrossMarginIncremental2";
        public const string GrossMarginPctTotal2 = "GrossMarginPctTotal2";
        public const string GrossMarginPctIncremental2 = "GrossMarginPctIncremental2";
        public const string VolumeTotal3 = "VolumeTotal3";
        public const string VolumeIncremental3 = "VolumeIncremental3";
        public const string GrossSalesTotal3 = "GrossSalesTotal3";
        public const string GrossSalesIncremental3 = "GrossSalesIncremental3";
        public const string NetSalesTotal3 = "NetSalesTotal3";
        public const string NetSalesIncremental3 = "NetSalesIncremental3";
        public const string COGSTotal3 = "COGSTotal3";
        public const string COGSIncremental3 = "COGSIncremental3";
        public const string GrossMarginTotal3 = "GrossMarginTotal3";
        public const string GrossMarginIncremental3 = "GrossMarginIncremental3";
        public const string GrossMarginPctTotal3 = "GrossMarginPctTotal3";
        public const string GrossMarginPctIncremental3 = "GrossMarginPctIncremental3";
        public const string NSDollerperLB1 = "NSDollerperLB1";
        public const string NSDollerperLB2 = "NSDollerperLB2";
        public const string NSDollerperLB3 = "NSDollerperLB3";
        public const string COGSperLB1 = "COGSperLB1";
        public const string COGSperLB2 = "COGSperLB2";
        public const string COGSperLB3 = "COGSperLB3";
        public const string Analysesincluded = "Analysesincluded";
        public const string ModifiedDate = "ModifiedDate";
        public const string ModifiedBy = "ModifiedBy";
        public const string FormSubmittedDate = "FormSubmittedDate";
        public const string FormSubmittedBy = "FormSubmittedBy";

        public const string Gate_DisplayName = "Gate";
        public const string BriefNumber_DisplayName = "Brief Number";
        public const string BriefName_DisplayName = "Brief Name";
        public const string BriefSummary_DisplayName = "Brief Summary";
        public const string Name_DisplayName = "Name";
        public const string AverageTargetMargin_DisplayName = "Average Target Margin";
        public const string DispConsFinInProjBrief_DisplayName = "Disp Cons Fin In Proj Brief";
        public const string VolumeTotal1_DisplayName = "Volume Total 1";
        public const string VolumeIncremental1_DisplayName = "Volume Incremental 1";
        public const string GrossSalesTotal1_DisplayName = "Gross Sales Total 1";
        public const string GrossSalesIncremental1_DisplayName = "Gross Sales Incremental 1";
        public const string NetSalesTotal1_DisplayName = "Net Sales Total 1";
        public const string NetSalesIncremental1_DisplayName = "Net Sales Incremental 1";
        public const string COGSTotal1_DisplayName = "COGS Total 1";
        public const string COGSIncremental1_DisplayName = "COGS Incremental 1";
        public const string GrossMarginTotal1_DisplayName = "Gross Margin Total 1";
        public const string GrossMarginIncremental1_DisplayName = "Gross Margin Incremental 1";
        public const string GrossMarginPctTotal1_DisplayName = "Gross Margin Pct Total 1";
        public const string GrossMarginPctIncremental1_DisplayName = "Gross Margin Pct Incremental 1";
        public const string VolumeTotal2_DisplayName = "Volume Total 2";
        public const string VolumeIncremental2_DisplayName = "Volume Incremental 2";
        public const string GrossSalesTotal2_DisplayName = "Gross Sales Total 2";
        public const string GrossSalesIncremental2_DisplayName = "Gross Sales Incremental 2";
        public const string NetSalesTotal2_DisplayName = "Net Sales Total 2";
        public const string NetSalesIncremental2_DisplayName = "Net Sales Incremental 2";
        public const string COGSTotal2_DisplayName = "COGS Total 2";
        public const string COGSIncremental2_DisplayName = "COGS Incremental 2";
        public const string GrossMarginTotal2_DisplayName = "Gross Margin Total 2";
        public const string GrossMarginIncremental2_DisplayName = "Gross Margin Incremental 2";
        public const string GrossMarginPctTotal2_DisplayName = "Gross Margin Pct Total 2";
        public const string GrossMarginPctIncremental2_DisplayName = "Gross Margin Pct Incremental 2";
        public const string VolumeTotal3_DisplayName = "Volume Total 3";
        public const string VolumeIncremental3_DisplayName = "Volume Incremental 3";
        public const string GrossSalesTotal3_DisplayName = "Gross Sales Total 3";
        public const string GrossSalesIncremental3_DisplayName = "Gross Sales Incremental 3";
        public const string NetSalesTotal3_DisplayName = "Net Sales Total 3";
        public const string NetSalesIncremental3_DisplayName = "Net Sales Incremental 3";
        public const string COGSTotal3_DisplayName = "COGS Total 3";
        public const string COGSIncremental3_DisplayName = "COGS Incremental 3";
        public const string GrossMarginTotal3_DisplayName = "Gross Margin Total 3";
        public const string GrossMarginIncremental3_DisplayName = "Gross Margin Incremental 3";
        public const string GrossMarginPctTotal3_DisplayName = "Gross Margin Pct Total 3";
        public const string GrossMarginPctIncremental3_DisplayName = "Gross Margin Pct Incremental 3";
        public const string NSDollerperLB1_DisplayName = "NS Doller per LB 1";
        public const string NSDollerperLB2_DisplayName = "NS Doller per LB 2";
        public const string NSDollerperLB3_DisplayName = "NS Doller per LB 3";
        public const string COGSperLB1_DisplayName = "COGS per LB 1";
        public const string COGSperLB2_DisplayName = "COGS per LB 2";
        public const string COGSperLB3_DisplayName = "COGS per LB 3";
        public const string Analysesincluded_DisplayName = "Analyses included";
        public const string ModifiedDate_DisplayName = "Modified Date";
        public const string ModifiedBy_DisplayName = "Modified By";
        public const string FormSubmittedDate_DisplayName = "Form Submitted Date";
        public const string FormSubmittedBy_DisplayName = "Form Submitted By";


    }
}
