using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Ferrara.Compass.Abstractions.Enum
{
    public enum XmlFileName
    {
        AllergenLookupData,
        BrandsLookupData,
        CaseTypesLookupData,
        CountryOfOriginLookupData,
        CustomersLookupData,
        DistributionCentersLookupData,
        DistributionDeploymentModesLookupData,
        KosherTypesLookupData,
        ManufacturingLocationsLookupData,

        MaterialGroup1LookupData,
        MaterialGroup2LookupData,
        MaterialGroup4LookupData,
        MaterialGroup5LookupData,
        PackagingComponentTypesLookupData,

        PackingLocationsLookupData,
        PlantLinesLookupData,
        ProcurementTypesLookupData,
        ProductHierarchyLevel1LookupData,
        ProductHierarchyLevel2LookupData,
        ProjectTypesLookupData,
        PMTProjectTypesLookupData,
        StageLookupData,
        RetailPackTypesLookupData,

        PrintStyleLookupData,
        FilmPrintStyleLookupData,
        FilmStyleLookupData,
        CorrugatedPrintStyleLookupData,
        ExternalGraphicsVendorsData,
        CriticalInitiativesData,
        PrinterSupplierData,

        ProjectCategoryData,
        TargetFCCMarginData,
        SAPBaseUOMData,
        PackUnitData,
        FlowThroughTypeData,
        MRPCData,
        ChannelData,

        SubstrateData,
        SubstrateColorData,
        MakePackTransfersData,
        PurchasedIntoCenterData,
        FilmSubstrateData,

        CoManufacturersData,
        CoManufacturingClassificationsData,
        CoPackersData,
        ManufacturerCountryOfOriginData,
        SupplierLeadTimeData,
        PackTrialResultData,
        SecondaryInitialReviewDecisions,
        OrderUnitofMeasure,
        Incoterms,
        PRDateCategory,
        BackSeamsData,
        TimelineTypesLookupData,
        CostingUnitData,
        NutrientTypeData,
        NutrientQuantityContainedTypeData,
        NutrientQuantityUOMdata,
        DailyValueIntakePctMeasPrecCode,
        PreparationStateData,
        ServingSizeData,

        ProductTypeData,
        AlternateClassificationSchemeData,
        GS1tradeKeyCodeData,
        DataCarrierTypeCodeData,
        TradeChannelData,
        BrandOwnerGLNdata,
        ProjectTypesSubCategoryLookup,
        PercentagesLookup,
        GoodSourceLookup,
        NaturalFlavorsLookup,
        NaturalColorsLookup,
        GlutenFreeLookup,
        GMOClaimLookup,
        MadeInUSAClaimLookup,
        FilmUnWindLookup,
        StageGateDesignDelivLookup,
        StageGateDevelopDelivLookup,
        StageGateIndustrializDelivLookup,
        StageGateLaunchDelivLookup,
        StageGatePostLaunchDelivLookup,
        StageGateValidateDelivLookup,
        StageGateStageStatusLookup,
        StageGateSGMeetingLookup,
        GateDetailColorsLookup,
        OverallRiskLookup,
        OverallStatusLookup,
        CompPurchasedIntoLocationsLookup,
        BusinessFunctionsLookup,
        TaskCheckboxesLookup,
        BioEngineeringLabelingcceptableLookup,
        BioEngineeringLabelingRequiredLookup
    }
}
